In [28]:
import pandas as pd
import numpy as np
original_df = pd.read_csv('gwas_4_alz_original_results_final.csv')
results_df = pd.read_csv('gwas_4_alz_intermediate_files/merged_result_df.csv')
results_df = pd.read_csv('gwas_4_alz_result_files/filtered_snps_sd=0.0.csv')


original_df.head()

,Genomic Locus,Position (GRCh37),Lead variant,A1,A1 frequency,P,N,Match (Manual)
0,1,1:985377,rs113020870,T,0.0041,3.830000e-08,776379,N
1,2,1:207750568,rs679515,C,0.8200,2.420000e-25,762176,Y
2,3,2:106235428,rs115186657,C,0.0035,1.330000e-08,727537,N
3,4,2:127891427,rs4663105,C,0.4100,3.920000e-58,1078540,Y
4,5,2:234082577,rs7597763,C,0.4500,4.650000e-09,819541,Y

In [29]:
original_df[['chr', 'pos']] = original_df['Position (GRCh37)'].str.split(':', expand=True)
original_df['pos'] = pd.to_numeric(original_df['pos'])
original_df['left_border'] = np.maximum(original_df['pos'] - 500000,0)
original_df['right_border'] = np.maximum(original_df['pos'] + 500000,0)
original_df

,Genomic Locus,Position (GRCh37),Lead variant,A1,A1 frequency,P,N,Match (Manual),chr,pos,left_border,right_border
0,1,1:985377,rs113020870,T,0.0041,3.830000e-08,776379,N,1,985377,485377,1485377
1,2,1:207750568,rs679515,C,0.8200,2.420000e-25,762176,Y,1,207750568,207250568,208250568
2,3,2:106235428,rs115186657,C,0.0035,1.330000e-08,727537,N,2,106235428,105735428,106735428
3,4,2:127891427,rs4663105,C,0.4100,3.920000e-58,1078540,Y,2,127891427,127391427,128391427
4,5,2:234082577,rs7597763,C,0.4500,4.650000e-09,819541,Y,2,234082577,233582577,234582577
5,6,4:11014822,rs4504245,G,0.7900,5.230000e-12,1080458,Y,4,11014822,10514822,11514822
6,7,5:150432388,rs871269,T,0.3200,1.370000e-09,1089904,Y,5,150432388,149932388,150932388
7,8,5:156526331,rs6891966,G,0.7700,7.910000e-10,1089230,N,5,156526331,156026331,157026331
8,9,6:32583813,rs1846190,A,0.3000,2.660000e-14,754040,Y,6,32583813,32083813,33083813
9,10,6:40942196,rs187370608,G,0.9970,1.260000e-25,791668,Y,6,40942196,40442196,41442196
10,11,6:47552180,rs9369716,T,0.2700,1.700000e-17,1052285,Y,6,47552180,47052180,48052180
11,12,7:12268758,rs5011436,C,0.4100,2.700000e-09,1123678,Y,7,12268758,11768758,12768758
12,13,7:99932049,rs7384878,T,0.6900,9.410000e-16,1084138,Y,7,99932049,99432049,100432049
13,14,7:143104331,rs3935067,G,0.6200,4.690000e-11,1117025,Y,7,143104331,142604331,143604331
14,15,8:27466315,rs1532278,T,0.3900,1.570000e-22,1126563,Y,8,27466315,26966315,27966315
15,16,8:145108151,rs61732533,G,0.9500,3.140000e-09,1122653,Y,8,145108151,144608151,145608151
16,17,10:11718713,rs7912495,G,0.4600,7.680000e-15,1120367,Y,10,11718713,11218713,12218713
17,18,10:61738152,rs7902657,T,0.5400,3.680000e-08,1126388,Y,10,61738152,61238152,62238152
18,19,11:47380340,rs3740688,T,0.5400,8.780000e-09,1123185,Y,11,47380340,46880340,47880340
19,20,11:60021948,rs1582763,G,0.6200,3.400000e-33,1125804,Y,11,60021948,59521948,60521948
20,21,11:85800279,rs561655,G,0.3500,1.240000e-26,1126563,Y,11,85800279,85300279,86300279
21,22,11:121435587,rs11218343,T,0.9600,1.330000e-13,1125100,Y,11,121435587,120935587,121935587
22,24,14:92938855,rs12590654,G,0.6700,6.630000e-17,1116967,Y,14,92938855,92438855,93438855
23,25,15:59057023,rs602602,T,0.7000,6.220000e-15,1124268,Y,15,59057023,58557023,59557023
24,26,15:63569902,rs117618017,T,0.1300,7.000000e-12,889854,Y,15,63569902,63069902,64069902
25,27,17:4969940,rs7209200,T,0.3300,3.180000e-08,1125637,N,17,4969940,4469940,5469940
26,28,17:42442344,rs708382,T,0.6100,1.980000e-09,1125622,Y,17,42442344,41942344,42942344
27,29,17:47450775,rs28394864,G,0.5400,4.900000e-10,1084218,Y,17,47450775,46950775,47950775
28,30,17:56409089,rs2632516,G,0.5400,7.460000e-10,1082451,N,17,56409089,55909089,56909089
29,31,17:61545779,rs6504163,T,0.6100,1.230000e-09,1083145,Y,17,61545779,61045779,62045779
30,32,19:1050874,rs12151021,G,0.6800,2.810000e-15,1082434,Y,19,1050874,550874,1550874
31,33,19:45411941,rs429358,T,0.8400,1.000000e-30,1126190,Y,19,45411941,44911941,45911941
32,34,19:49213504,rs2452170,G,0.4700,1.720000e-08,1088626,N,19,49213504,48713504,49713504
33,35,19:51737991,rs1354106,G,0.3700,2.210000e-10,716038,Y,19,51737991,51237991,52237991
34,36,19:54825174,rs1761461,C,0.4900,1.560000e-09,1116336,N,19,54825174,54325174,55325174
35,37,20:54995699,rs6069737,T,0.0830,6.730000e-16,1087703,Y,20,54995699,54495699,55495699
36,38,21:27520931,rs2154482,T,0.4400,7.660000e-10,1124606,N,21,27520931,27020931,28020931

In [30]:
results_df.head()

,Unnamed: 0,pos,chr,p,snp,left_border,right_border
0,0,161187665,1,7.157343e-09,rs2070902,161097241,161185058
1,1,207750568,1,2.419694e-25,rs679515,207653395,207837946
2,2,127891427,2,6.723892e-55,rs4663105,127772047,127895487
3,3,234082577,2,1.887192e-08,rs7597763,233985913,234091158
4,4,11014822,4,5.039113e-13,rs4504245,10956511,11044972

In [31]:
print(set(results_df['snp']).intersection(set(original_df['Lead variant'])))
print(len(set(results_df['snp']).intersection(set(original_df['Lead variant']))))

{'rs7597763', 'rs11218343', 'rs871269', 'rs4504245', 'rs1532278', 'rs12590654', 'rs7384878', 'rs4663105', 'rs679515', 'rs6504163', 'rs3935067', 'rs28394864', 'rs3740688'}
13

In [32]:
def count_overlaps(df1, df2):
        
        overlap_count = 0
    
        # Iterate over all pairs of intervals
        for _, row1 in df1.iterrows():
            chr1 = int(row1['chr'])
            for _, row2 in df2.iterrows():
                chr2 = int(row2['chr'])
                # Check if the intervals overlap on the same chromosome
                if chr1==chr2 and row1['right_border'] >= row2['left_border'] and row1['left_border'] <= row2['right_border']:
                    overlap_count += 1
                    break
        return overlap_count

overlap_count = count_overlaps(results_df, original_df)
overlap_count

34